# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  networking = {
    hostName = "laptop";
    # domain = "";
    # hosts = {
    #   "1.2.3.4" = ["domain.tld" "domain2.tld"];
    # };
  };
  users.users.haris.hashedPassword = "";
}
